                <!-- Article 1 start -->

                <div class="line"></div>  <!-- Dividing line -->
                
                <article id="home"> <!-- The new article tag. The id is supplied so it can be scrolled into view. -->
                    <h2>Overview</h2>
                    
                    <div class="line"></div>
                    
                    <div class="articleBody clear">
                    
                        <figure> <!-- The figure tag marks data (usually an image) that is part of the article -->
                            <img src="/images/overview.jpg" width="600" height="320" />
                        </figure>                        
                        <p>Welcome to online bookstore!</p>
                        <p>
                        <video width="340" controls autoplay> 
                            <source src="/video/Bookstore.mp4" type="video/mp4" />
                        </video>
                        </p>                        
                    </div>
                </article>
                
                <!-- Article 1 end -->


                <!-- Article 2 start -->

                <div class="line"></div>
                
                <article id="about">
                    <h2>About us</h2>
                    
                    <div class="line"></div>
                    
                    <div class="articleBody clear">
                        <figure>
                            <img src="/images/about_us.jpg" width="620" height="340" />
                        </figure>                        
                        <p>We are an online book store. We have thousands of books in stock.
                        We can search the books by ISBN or author.
                        We accept Paypal and Visa Credit Cards.
                        We will ship the books within 1-2 business days.</p>
                        
                    </div>
                </article>
                
                <!-- Article 2 end -->
