<!--<script type="text/javascript" src="/js/site.js"></script>
<script type="text/javascript" src="/js/jquery-1.7.1.js"></script>
<script type="text/javascript" src="/js/jquery.datePicker.js"></script>
<script type="text/javascript" src="/js/jquery-ui-1.7.2.custom.min.js"></script>-->

<script type="text/javascript">
	$(function() {
		$("#birthday").datepicker();
  	});
</script>

<h2>Register a new member</h2>
<p>To register a new member, please complete this form below to and click submit.</p>

<?php
$this -> registerForm -> setAction($this -> url());
echo $this -> registerForm;
?>